services:
  postgresql:
    image: docker.io/bitnami/postgresql:16.4.0
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - 'C:/docker/postgres_data:/bitnami/postgresql'
  keycloak:
    image: docker.io/bitnami/keycloak:25.0.6
    ports:
      - "80:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_USER=postgres
      - KEYCLOAK_DATABASE_PASSWORD=postgres
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_LOG_LEVEL=DEBUG
    depends_on:
      - postgresql
  redis:
    image: docker.io/redis:7.4.0
    ports:
      - "6379:6379"
  eureka:
    image: docker.io/steeltoeoss/eureka-server:4.1.1
    ports:
      - "8761:8761"
  activemq:
    image: webcenter/activemq:5.14.3
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    ports:
      - "8161:8161"
      - "61616:61616"
      - "61613:61613"
    volumes:
      - 'C:/docker/activemq/conf/activemq.xml:/opt/activemq/conf/activemq.xml'

  mongodb:
    image: mongo:8.0.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - 'C:/docker/mongo_data:/data/db'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://mongoadmin:secret@mongodb:27017/

volumes:
  postgresql_data:
    driver: local
  mongo_data:
    driver: local
