services:
  postgresql:
    image: docker.io/bitnami/postgresql:16.4.0
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - 'C:/docker/postgres_data:/bitnami/postgresql'
  keycloak:
    image: docker.io/bitnami/keycloak:25.0.6
    ports:
      - "80:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_USER=postgres
      - KEYCLOAK_DATABASE_PASSWORD=postgres
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_LOG_LEVEL=DEBUG
    depends_on:
      - postgresql
  redis:
    image: docker.io/redis:7.4.0
    ports:
      - "6379:6379"
  eureka:
    image: docker.io/steeltoeoss/eureka-server:4.1.1
    ports:
      - "8761:8761"
volumes:
  postgresql_data:
    driver: local
