spring:
  config:
    import: "classpath:dev/confidential-dev.yaml"
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_crm_system_dev
    username: postgres
