spring:
  config:
    activate:
      on-profile: e2e
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
  data:
    mongodb:
      uri: mongodb://testuser:testpassword@mongodb:27017/admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
cors:
  allowed-origins:
    - "http://localhost"
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "PATCH"
    - "DELETE"
  allowed-headers:
    - "Authorization"
    - "Content-Type"
keycloak:
  url: http://keycloak:8080
  realm: gym-crm-system-realm

server:
  port: 80