spring:
  config:
    import: "classpath:local/confidential-local.yaml"
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_crm_system
    username: postgres
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost/realms/gym-crm-system-realm
            authorization-uri: http://localhost/realms/gym-crm-system-realm/protocol/openid-connect/auth
            token-uri: http://localhost/realms/gym-crm-system-realm/protocol/openid-connect/token
            user-info-uri: http://localhost/realms/gym-crm-system-realm/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost/realms/gym-crm-system-realm/protocol/openid-connect/certs
            user-name-attribute: preferred_username
        registration:
          keycloak:
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
springdoc:
  swagger-ui:
    oauth2-redirect-url: http://localhost:5555/swagger-ui/oauth2-redirect.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
cors:
  allowed-origins:
    - "http://localhost"
    - "http://localhost:5555"
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "PATCH"
    - "DELETE"
  allowed-headers:
    - "Authorization"
    - "Content-Type"