spring:
  config:
    import: "classpath:stg/confidential-stg.yaml"
    activate:
      on-profile: stg
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_crm_system_stg
    username: postgres
  data:
    redis:
      host: localhost
      port: 6379
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    queues:
      trainer-workload: trainer-workload
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      keycloak-service: http://localhost:8080/
      keycloak-auth: http://localhost:8080/
cors:
  allowed-origins:
    - "http://localhost"
    - "http://localhost:5555"
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "PATCH"
    - "DELETE"
  allowed-headers:
    - "Authorization"
    - "Content-Type"

keycloak:
  admin:
    username: gym-crm-system-admin
    client-id: gym-crm-microservice-admin
  user:
    client-id: gym-crm-microservice-client
  url: http://localhost
  realm: gym-crm-system-realm
