spring:
  config:
    import: "classpath:prod/confidential-prod.yaml"
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_crm_system_prod
    username: postgres
  data:
    redis:
      host: localhost
      port: 6379
