spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  main:
    allow-bean-definition-overriding: true
  config:
    import: "classpath:dev/confidential-dev.yaml"
    activate:
      on-profile: dev
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
cors:
  allowed-origins:
    - "http://localhost"
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "PATCH"
    - "DELETE"
  allowed-headers:
    - "Authorization"
    - "Content-Type"
keycloak:
  url: http://keycloak:8080
  realm: gym-crm-system-realm

server:
  port: 80