spring:
  config:
    import: "classpath:stg/confidential-stg.yaml"
    activate:
      on-profile: stg
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_crm_system_stg
    username: postgres
