spring:
  config:
    import: "classpath:local/confidential-local.yaml"
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_crm_system
    username: postgres
  data:
    redis:
      host: localhost
      port: 6379