spring:
  config:
    import: "classpath:dev/confidential-dev.yaml"
    activate:
      on-profile: dev
  datasource:
#    url: jdbc:postgresql://postgresql:5432/gym_crm_system
#    username: postgres
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      schema-locations: classpath:db/initDBH2.sql
      data-locations: classpath:db/populateDB.sql
      mode: always
  data:
    redis:
      host: redis
      port: 6379
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    queues:
      trainer-workload: trainer-workload
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    metadata-map:
      keycloak-service: http://keycloak:8080/
      keycloak-auth: http://keycloak:8080/
cors:
  allowed-origins:
    - "http://localhost"
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "PATCH"
    - "DELETE"
  allowed-headers:
    - "Authorization"
    - "Content-Type"

keycloak:
  admin:
    username: gym-crm-system-admin
    client-id: gym-crm-microservice-admin
  user:
    client-id: gym-crm-microservice-client
  url: http://keycloak:8080
  realm: gym-crm-system-realm

server:
  port: 80