spring:
  application:
    name: crm-system
  config:
    import:
      - "classpath:local/application-local.yaml"
      - "classpath:dev/application-dev.yaml"
      - "classpath:stg/application-stg.yaml"
      - "classpath:prod/application-prod.yaml"

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20

  sql:
    init:
      schema-locations: classpath:db/initDB.sql
      data-locations: classpath:db/populateDB.sql
      mode: always
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

server:
  port: 0
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
eureka:
  instance:
    preferIpAddress: true

logging:
  level:
    root: INFO
    com.annakirillova.crmsystem: DEBUG
    org.zalando.logbook: TRACE

springdoc:
  show-actuator: true
  swagger-ui:
    path: /

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      trainerWorkloadService:
        registerHealthIndicator: true
        slidingWindowSize: 6
        permittedNumberOfCallsInHalfOpenState: 4
        waitDurationInOpenState: 20s
        failureRateThreshold: 60
      keycloak:
        registerHealthIndicator: true
        slidingWindowSize: 6
        permittedNumberOfCallsInHalfOpenState: 4
        waitDurationInOpenState: 20s
        failureRateThreshold: 60
logbook:
  format:
    style: http