spring:
  application:
    name: trainer-workload-service
  config:
    import:
      - "classpath:local/application-local.yaml"
      - "classpath:dev/application-dev.yaml"
      - "classpath:stg/application-stg.yaml"
      - "classpath:prod/application-prod.yaml"
      - "classpath:e2e/application-e2e.yaml"
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20

  data:
    mongodb:
      auto-index-creation: true

logging:
  level:
    root: INFO
    com.annakirillova.trainerworkloadservice: DEBUG
    org.zalando.logbook: TRACE

springdoc:
  show-actuator: true
  swagger-ui:
    path: /

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

logbook:
  format:
    style: http